trigger:
- main  # You can change this to the branch you want to trigger the pipeline on

pr:
- '*'  # This triggers the pipeline on pull requests as well

pool:
  name: $(POOL)

steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(KNOWN_HOST)
      sshPublicKey: $(PUBLIC_KEY)
      sshPassphrase: $(PASS_PHRASE)
      sshKeySecureFile: $(SSH_SECURE_FILE)
  - script: |
      ssh -i ~/.ssh/$(SSH_SECURE_FILE) $(SERVER) -p $(PORT) "bash -c \
        cd ~/\
        export SSH_ASKPASS=echo $(REPO_KEY_PASS_PHRASE)\
        git clone $(GIT_CLONE)\
      "
    displayName: 'Running remote server scripts'
