trigger:
- main  # You can change this to the branch you want to trigger the pipeline on

pool:
  name: $(POOL)

steps:
- script: |
    apt-get update -y
    apt-get install docker-compose-plugin -y
  displayName: 'Install docker-compose'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build -d'