trigger:
- main  # You can change this to the branch you want to trigger the pipeline on

pool:
  name: $(POOL)

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(KNOWN_HOSTS)'
    sshPublicKey: '$(SSH_PUBLIC_KEY)'
    sshPassphrase: '$(PASSPHRASE)'
    sshKeySecureFile: '$(SSH_KEY)'
    addEntryToConfig: true
    configHostAlias: ssh.dev.azure.com
    configHostname: ssh.dev.azure.com
    configUser: git
- script: |
    # cp /tmp/$(SSH_KEY) ~/.ssh/
    # ls ~/.ssh/
    # git add ~/.ssh/$(SSH_KEY)
    # cd /home
    # chmod 600 /azp/_work/_temp/id_rsa_azp
    chmod 600 /azp/_work/_temp/$(SSH_KEY)
    # sshpass -p $(SSH_PASSPHRASE)
    # ssh-add /azp/_work/_temp/$(SSH_KEY)
    git clone --verbose $(REPO) 
  displayName: 'Clone repository'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build -d'