trigger:
- main  # You can change this to the branch you want to trigger the pipeline on

pool:
  name: $(POOL)

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(KNOWN_HOSTS)'
    sshPublicKey: '$(SSH_PUBLIC_KEY)'
    sshPassphrase: '$(SSH_KEY_PASS_PHRASE)'
    sshKeySecureFile: '$(SSH_KEY)'
    addEntryToConfig: true
    configHostAlias: ssh.dev.azure.com
    configHostname: ssh.dev.azure.com
    configUser: git
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(KNOWN_HOSTS)'
    sshPublicKey: '$(SERVER_PUBLIC_KEY)'
    sshPassphrase: '$(SERVER_PASS_PHRASE)'
    sshKeySecureFile: '$(SERVER_KEY)'
- script: |
    # chmod 600 /azp/_work/_temp/$(SSH_KEY)
    git clone --verbose $(REPO)
  displayName: 'Clone repository'
- script: 
    ssh $(HOSTNAME) -p 4089 'touch ~/cooper'
  displayName: 'Remote server execution'    
