trigger:
- main  # You can change this to the branch you want to trigger the pipeline on

pr:
- '*'  # This triggers the pipeline on pull requests as well

pool:
  name: $(POOL)

steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(KNOWN_HOST)
      sshPublicKey: $(PUBLIC_KEY)
      sshPassphrase: $(PASS_PHRASE)
      sshKeySecureFile: $(SSH_SECURE_FILE)
  - script: |
      ssh -v -i ~/.ssh/$(SSH_SECURE_FILE) $(SERVER) -p $(PORT) "touch ~/agent_connected"
      ssh -v -i ~/.ssh/$(SSH_SECURE_FILE) $(SERVER) -p $(PORT) "touch ~/agent_connected_2"
    displayName: 'Running remote server scripts'
